### ISSUE TITLE
error in process sentinel: Wrong type argument: hash-table-p, nil

### ISSUE THREAD

**Issue by girvain** [atilaneves/cmake-ide#170] opened 2018-06-11 21:36 UTC
Hey, after I upgraded from emacs 25.2 to 25.3 I have a problem of having to set the build dir each time I open a project. I get this in the messages,

cmake-ide [Mon Jun 11 22:28:08 2018]: Making directory /tmp/cmake5550LBR
cmake-ide [Mon Jun 11 22:28:09 2018]: Running cmake for src path /home/gavin/Downloads/cplusplus-fundamentals-c17/09/demos/Demo/Begin/Accumulator/Accumulator/ in build path /tmp/cmake5550LBR/
cmake-ide [Mon Jun 11 22:28:09 2018]: Finished running CMake
cmake-ide [Mon Jun 11 22:28:09 2018]: Non-existent compilation DB file /tmp/cmake5550LBR/compile_commands.json
error in process sentinel: cide--idb-file-to-obj: Wrong type argument: hash-table-p, nil
error in process sentinel: Wrong type argument: hash-table-p, nil
Loading /home/gavin/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
Mark set
Quit
Mark set

The weird part is it all works just fine it's just that I get this error message. So it seems that its loading from the /tmp directory but i have no idea why it keeps resorting back to this on a new session.
Thanks

Also, I think the issue is related to the CMakeCache.txt because if I delete this before starting there is no errors. Works perfect on my mac fwi, this is on Ubuntu.

**Comment by atilaneves** [comment] 2018-06-12 14:17
I think it'll be hard for me to figure this out without more information. It doesn't help that my Emacs is version 26.1.

**Comment by girvain** [comment] 2018-06-12 22:39
I sort of fixed the issue. Not entirely sure what the problem was but with a complete re-compile or new project I get this 
PointersAndReferences.cpp has auto save data; consider M-x recover-this-file
cmake-ide [Tue Jun 12 23:32:16 2018]: Converting JSON CDB /home/gavin/src/stringent/build/compile_commands.json to IDB
cmake-ide [Tue Jun 12 23:32:16 2018]: Setting flags for file /home/gavin/Downloads/cplusplus-fundamentals-c17/10/demos/Demo/Before/PointersAndReferences/PointersAndReferences/PointersAndReferences.cpp
cmake-ide [Tue Jun 12 23:32:17 2018]: Running rc for rtags
Loading /home/gavin/.emacs.d/recentf...done

Only thing is the Converting JSON CDB .... etc. It never used to do that, it would just load with the Running rc for rtags message. When I take this line out of my emacs,
  (setq cmake-ide-build-dir
         (expand-file-name "~/src/stringent/build"))
it causes the project to be be made in the tmp/cmake2342.... folders and then that's when I get the errors from above. 

Overall though, despite not understanding why this conversion is happening, it works great again and I love the package so thanks

**Comment by atilaneves** [comment] 2018-06-12 23:46
Thanks for commenting. It looks like it only surfaces when it's using a temporary directory. I'll look into it.

**Comment by atilaneves** [comment] 2018-06-13 22:54
I couldn't reproduce this. If you find anything else, please let me know. For now I'll close it.

**Closed by atilaneves** 2018-06-13 22:54 UTC
Labels: bug, help wanted, incomplete, worksforme

**Comment by LucaMarconato** [comment] 2018-08-29 14:47
I am getting this error. I am trying to understand how to reproduce it.

Activating `toggle-debug-on-error` I got this backtrace, which may help.

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("/Users/username/project/main.cpp" nil)
  cide--idb-file-to-obj(nil "/Users/username/project/main.cpp")
  cide--set-flags-for-file(nil #<buffer main.cpp>)
  #f(compiled-function (x) #<bytecode 0x445c0fa1>)(#<buffer main.cpp>)
  mapc(#f(compiled-function (x) #<bytecode 0x445c0fa1>) (#<buffer main.cpp>))
  cide--on-cmake-finished()
  #f(compiled-function (process event) #<bytecode 0x4050d971>)(#<process cmake> "finished\n")

```
