### ISSUE TITLE
Set only needed flags to header files based on subprojects

### ISSUE THREAD

**Issue by sezaru** [atilaneves/cmake-ide#38] opened 2016-01-07 01:41 UTC
When cmake-ide fails to find the corresponding cpp file for a header, it includes everything to the hdr-flags variable.

But sometime this is not the best approach since it can lead to false-negatives of flycheck.

This can happen when your cmake project contains subprojects (added by add_subdirectory).

For example, you have a project with 2 subprojects, subproj1 and subproj2.

Now, subproj2 have a dependecy with libxml, so when you open a cpp file of subproj2, compile_commands.json will have the necessary includes to libxml in it.

Now, let's say you open a hpp file of subproj1 and add a #include \<libxml/libxml.h\>  to it, since subproj1 doesn't have a dependency with libxml, it will fail to find this header and fail in compilation.

But since cmake-ide will add all the possible includes, it will include the libxml include path to it and flycheck will think that the #include above is ok and not a error.

Now, for the solution, I think we can use the directory information from compile_commands.json, as far as I understand it, this parameter will show the root of the project in it, for example, let's say I have a file test.cpp in subproj2, with this path /project/subproj2/src/Tests/test.cpp, in the json file, the directory parameter for this file will be:
"directory" : "/tmp/cmakef2342e32e32/subproj2"

Actually, every file in subproj2 will have this same directory, and files of subproj1 will have the path to subproj1.

The idea is to group the includes based in this directory parameter, what cmake can do is create an map of all the flags of all files for each subproject, and when a file is opened, it will see if the file is inside some subproject and only use their flags, so, for example, if I opened a file Test.hpp located in /project/subproj2/includes/Tests/test.hpp", cmake-ide will see that this file is inside the subproj2 directory and so it belongs to subproj2, and as consequence will set all flags of subproj2 (but will not set the flags of subproj1).

Do you think this is a good solution for this? And a easy one to implement?

Thanks

**Comment by atilaneves** [comment] 2016-01-07 09:34
I understand the issue. The changes I made yesterday were to alleviate it. The real problem is that I'm not sure what the best thing to do is. Headers don't have flags because they're not usually compiled separately (pre-compiled headers being the exception). So what to do?

Originally I punted and used every flag. After a few months living with this, it's clear it only works for small/toy projects. Yesterday I added a change to use the corresponding source file if there is one. But the general problem remains.

As for your `"directory"` idea, it won't work. All that does is specify the directory where the file is compiled from, it has nothing to do with `add_subdirectory` so that won't work.

I'll close this issue since the problem is more involved and will require more heavy-duty work.

**Closed by atilaneves** 2016-01-07 09:34 UTC

**Comment by sezaru** [comment] 2016-01-07 10:56
Are you sure about the directory usage? I checked all my projects and cmake always use the project directory as the directory parameter.

What I mean is that if a file is inside project/subproj2/src/dir1/dir2/dir3/file.cpp, the directory parameter will contain subproj2 directory in /tmp/cmake32423423, the file parameter is the one that will have the fullpath.

I made a example project to better show what I mean, I have my test root project with it CMakelists.txt:

    cmake_minimum_required(VERSION 3.2.0)
    project(Test)

    add_subdirectory(proj1)
    add_subdirectory(proj2)

    file (GLOB_RECURSE sources ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp)
    add_executable(${PROJECT_NAME} ${sources})

Inside test/src I have a single file with a main.

Now, I have 2 subprojects, proj1 and proj2, both added with the add_subdirectory as shown above. Each subproject contains 1 cpp file and the CMakeLists.txt for then looks like this:

    cmake_minimum_required(VERSION 3.2.0)
    project(project1)

    file (GLOB_RECURSE sources ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp)
    add_library(${PROJECT_NAME} SHARED ${sources})

In the case of proj2, it's the same CMakeLists.txt but the project name is project2.

So, after running cmake with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON, I got this compile_commands.json:

    [
    {
      "directory": "/home/devel/test/build",
      "command": "/usr/bin/c++      -o CMakeFiles/Utils.dir/src/dir1/dir2/file.cpp.o -c /home/devel/test/src/dir1/dir2/file.cpp",
      "file": "/home/devel/test/src/dir1/dir2/file.cpp"
    },
    {
      "directory": "/home/devel/test/build/proj1",
      "command": "/usr/bin/c++   -Dproject1_EXPORTS -fPIC   -o CMakeFiles/project1.dir/src/dir1/file2.cpp.o -c /home/devel/test/proj1/src/dir1/file2.cpp",
      "file": "/home/devel/test/proj1/src/dir1/file2.cpp"
    },
    {
      "directory": "/home/devel/test/build/proj2",
      "command": "/usr/bin/c++   -Dproject2_EXPORTS -fPIC   -o CMakeFiles/project2.dir/src/dir1/file2.cpp.o -c /home/devel/test/proj2/src/dir1/file2.cpp",
      "file": "/home/devel/test/proj2/src/dir1/file2.cpp"
    }
    ]

As you can see, when the file is part of proj2, directory parameter will be  "/home/devel/test/build/proj2", when the file is part of proj1, the directory parameter will be "/home/devel/test/build/proj1", and when the file is part of the root project, the directory parameter will be "/home/devel/test/build".

Ignoring the path /home/devel/test/build, you can see that /home/devel/test/proj2/src/dir1/file2.cpp is part of proj2, /home/devel/test/proj1/src/dir1/file2.cpp is part of proj1 and /home/devel/test/src/dir1/dir2/file.cpp is part of the root proj.

when it comes to headers files, let's say I have a file in  /home/devel/test/proj1/includes/dir1/file2.hpp, since it is inside proj1 directory, it will be part of proj1 and I will know what flags to set to it.

Maybe I'm missing something, but I just checked the compile_commands.json in some pretty big projects I have and the directory parameter always maintains this structured I showed.

**Comment by atilaneves** [comment] 2016-01-07 13:07
Interesting. It seems that the difference is declaring `project`. I don't have that in my project and that's why the directory is always the same: it's the same project. It'll take a while to figure this out I think.

**Comment by sezaru** [comment] 2016-01-07 13:30
I think if you only have one project, it's okay to have all the includes, it will only be a problem (of false-negatives), if you have multiples add_executable or add_library that include different paths, but for this I can't see a solution too.

In my case the subprojects are like modules that generate libs that are dependencies for other modules, and so on.

I will try to make this changes in my fork when I have some spare time (can't promisse anything since my knowledge of elisp is very poor) to see if works great.
