### ISSUE TITLE
cmake-ide-cmake-opts can't contain parameters with spaces

### ISSUE THREAD

**Issue by andrmuel** [atilaneves/cmake-ide#181] opened 2018-10-10 19:52 UTC
Due to the 'split-string' in `cide--run-cmake-impl`, it is not possible to have a space in a parameter in `cmake-ide-cmake-opts` (e.g. "-DCONF_FILES=foo.conf bar.conf").

My workaround for the moment is to allow passing the parameters as lists:

    (defun cide--run-cmake-impl (project-dir cmake-dir)
      "Run the CMake process for PROJECT-DIR in CMAKE-DIR."
      (when project-dir
        (let ((default-directory cmake-dir))
          (cide--message "Running cmake for src path %s in build path %s" project-dir cmake-dir)
          (apply 'start-process (append (list "cmake" "*cmake*" cmake-ide-cmake-command)
                                        (if (listp cmake-ide-cmake-opts) cmake-ide-cmake-opts (split-string cmake-ide-cmake-opts))
                                        (list "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" project-dir))))))
    
    (defun cide--project-key ()
      "Return a unique key for a project based on the project dir and cmake options."
      (let ((project-dir (cide--locate-project-dir)))
        (when project-dir
          ;; if no project-dir, then get-project-key is called from a non cmake project dir, simply ignore
          (replace-regexp-in-string "[-/= ]" "_"  (concat (expand-file-name project-dir)
                                                          (if (listp cmake-ide-cmake-opts) (string-join cmake-ide-cmake-opts " ") cmake-ide-cmake-opts))))))

Maybe this could be added to cmake-ide?

**Comment by atilaneves** [comment] 2018-10-20 17:07
What's the use case for having a space in the option?

**Comment by atilaneves** [comment] 2018-10-22 13:11
I looked at your original example again and `-DCONF_FILES=foo.conf bar.conf` won't work at all with clang. It'll be just one `#define` (foo.conf). I don't know about your CMake option but unless there are quotes around the space-delimited list, that won't work either.

Are you using an old version of `cmake-ide`? It doesn't use `split-string` but `split-string-and-unquote`. I explained the history why in my comment on issue #177

**Comment by andrmuel** [comment] 2018-10-22 22:14
I was using cmake-ide-20180713; I see the split-string-and-unquote only 
in cide--split-command (which as I understand is not relevant for 
cmake-ide-cmake-opts).

I actually started out with something like -DCONF_FILES=\"foo.conf 
bar.conf\", but the only way I could actually get it to work is as 
described above.

The actual example I'm working with is the Zephyr OS 
(https://github.com/zephyrproject-rtos/zephyr), and my actual config is

(setq-local cmake-ide-cmake-opts '("-GNinja" "-DBOARD=nrf52840_pca10056" 
"-DCONF_FILE=prj.conf overlay-bt.conf"))

Looking at Zephyr itself, I see in cmake/kconfig.cmake:

string(REPLACE " " ";" CONF_FILE_AS_LIST "${CONF_FILE}")

Maybe this is the reason why I don't just get a #define foo.conf.

**Comment by atilaneves** [comment] 2018-10-23 14:19
Sorry, I misread your issue. I now understand what you mean.

The problem is that `cmake-ide-cmake-opts` should never have been a string but instead a list of strings. I didn't add that one and didn't think it through when I merged it.

**Closed** 2018-10-23 14:30 UTC
